# Generated by Django 6.0.3 on 2026-03-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=10)),
                ('grade', models.IntegerField(default=0)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
    ]
