# Generated by Django 6.0.3 on 2026-03-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
