# Generated by Django 6.0.3 on 2026-03-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_created_at_student_email_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
