# Generated by Django 6.0.3 on 2026-03-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='departments/logo'),
        ),
    ]
