# Generated by Django 6.0.3 on 2026-03-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pre_requisites',
            field=models.ManyToManyField(blank=True, related_name='pre_requisites', to='courses.course'),
        ),
    ]
